// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6oGkGS0k0NyeVB4blnsQGkQWbflFv29U',
    appId: '1:386019354494:web:11ba2b4ade0691d72ff52f',
    messagingSenderId: '386019354494',
    projectId: 'linkupfirebase',
    authDomain: 'linkupfirebase.firebaseapp.com',
    storageBucket: 'linkupfirebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClRIdgemymqbB69Y40fjum57yVxpEVsyo',
    appId: '1:386019354494:android:76f9cc16902140d52ff52f',
    messagingSenderId: '386019354494',
    projectId: 'linkupfirebase',
    storageBucket: 'linkupfirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTM2trdWKmwEkj13XbOTDEEInUYSf3Luc',
    appId: '1:386019354494:ios:ba09e490f83806172ff52f',
    messagingSenderId: '386019354494',
    projectId: 'linkupfirebase',
    storageBucket: 'linkupfirebase.firebasestorage.app',
    iosBundleId: 'com.example.signup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTM2trdWKmwEkj13XbOTDEEInUYSf3Luc',
    appId: '1:386019354494:ios:ba09e490f83806172ff52f',
    messagingSenderId: '386019354494',
    projectId: 'linkupfirebase',
    storageBucket: 'linkupfirebase.firebasestorage.app',
    iosBundleId: 'com.example.signup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6oGkGS0k0NyeVB4blnsQGkQWbflFv29U',
    appId: '1:386019354494:web:0ac82ba47b6a6e832ff52f',
    messagingSenderId: '386019354494',
    projectId: 'linkupfirebase',
    authDomain: 'linkupfirebase.firebaseapp.com',
    storageBucket: 'linkupfirebase.firebasestorage.app',
  );
}
